version: "3"
services:
  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
  ethlogspy:
    build: .
    container_name: ethlogspy
    environment:
      - NODE_HOST=geth.dappnode
      - NODE_PORT=8546
      - CORS_ORIGIN=*
      - BLOCK_NUMBER=0
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    restart: unless-stopped
    image: "ethlogspy.ethlogspy.public.dappnode.eth:0.1.0"
