mongo:
  connection: "mongodb://mongo:27017" # mongodb connection string
  db_name: "ethlogspy" # mongodb database name
redis:
  host: "redis" # redis host 
  port: 6379 # redis port
  password: "" # redis password
  db: 0 # redis db