mongo:
  connection: "mongodb://mongo:27017"
  db_name: "ethlogspy"
node:
  host: "host.docker.internal"
  port: 7545
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
server:
  block_number: 0
