contracts:
  - address: ""
  - signatures:
    - "ItemSet(bytes32,bytes32)"
mongo:
  connection: "mongodb://localhost:27017"
  db_name: "ethlogspy"
node:
  host: "localhost"
  port: 8535
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
server:
  port: 8080